[versions]
freefair = '8.1.0'

[libraries]
ihub-core = { module = 'pub.ihub.lib:ihub-core' }
dependency-management = { module = 'io.spring.gradle:dependency-management-plugin' }
freefair-utils = { module = 'io.freefair.gradle:plugin-utils', version.ref = 'freefair' }
freefair-git = { module = 'io.freefair.gradle:git-plugin', version.ref = 'freefair' }
freefair-lombok = { module = 'io.freefair.gradle:lombok-plugin', version.ref = 'freefair' }
freefair-github = { module = 'io.freefair.gradle:github-plugin', version.ref = 'freefair' }
freefair-settings = { module = 'io.freefair.gradle:settings-plugin', version.ref = 'freefair' }
ben-manes-versions = { module = 'com.github.ben-manes:gradle-versions-plugin' }
byte-buddy = { module = 'gradle.plugin.net.bytebuddy:byte-buddy-gradle-plugin' }
jmolecules-bytebuddy = { module = 'org.jmolecules.integrations:jmolecules-bytebuddy' }
johnrengelman-processes = { module = 'com.github.johnrengelman.processes:com.github.johnrengelman.processes.gradle.plugin' }
springdoc-openapi = { module = 'org.springdoc:springdoc-openapi-gradle-plugin' }
spring-boot = { module = 'org.springframework.boot:spring-boot-gradle-plugin' }
native = { module = 'org.graalvm.buildtools:native-gradle-plugin' }
kotlin = { module = 'org.jetbrains.kotlin:kotlin-gradle-plugin' }

[plugins]
testkit = { id = 'pl.droidsonroids.jacoco.testkit', version = '1.0.12' }
